[package]
name = "rust_type_to_c_type"
version = "0.1.0"
authors = ["Fu Tianhui <futh@seagroup.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]